service: default
runtime: java11
env: standard
runtime_config:
  jdk: openjdk11
env_variables:
  SPRING_PROFILES_ACTIVE: "production"
handlers:
- url: /api/.*
  script: this field is required, but ignored
manual_scaling:
  instances: 1